version: '3.8'
services:
  aws_import_tf:
    container_name: 'aws_import_tf'
    user: $DOCKER_UID:$DOCKER_GID
    build:
      context: .
      args:
        UID: $DOCKER_UID
        GID: $DOCKER_GID
        UNAME: $USER
    tty: true
    working_dir: '/home/$USER/terraform'
    volumes:
      - ./docker-aws-config:/home/$USER/.aws # docker에서 설정한 aws profile을 영구보존하기 위함. 싫다면 파일지우고, volume도 중단
      - .:/home/$USER/terraform
    entrypoint: |
      sh -e -c "
      sudo chown -R $USER /home/$USER
      /bin/sh
      "

networks:
  default:
    name: aws_import_tf_net