AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app

Globals:
  Function:
    Timeout: 3

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: ruby2.7
      Architectures:
        - x86_64
      Environment:
        Variables:
          SLACK_WEBHOOK_URL: https://hooks.slack.com/services/Incoming Webhooks URL적기
          SLACK_CHANNEL: 슬랙 채널명 적기
      Policies:
        - Statement:
          - Effect: 'Allow'
            Action:
              - 'logs:CreateLogGroup'
              - 'logs:CreateLogStream'
              - 'logs:PutLogEvents'
            Resource: 'arn:aws:logs:*:*:*'

  HelloWorldFunctionEventRule:
    Type: AWS::Events::Rule
    Properties: 
      Description: "For notifying CodePipeline deploy"
      EventPattern: 
        source:
          - aws.codepipeline
        detail-type:
          - CodePipeline Pipeline Execution State Change # https://docs.aws.amazon.com/codepipeline/latest/userguide/detect-state-changes-cloudwatch-events.html
        detail:
          state:
            - STARTED
            - SUCCEEDED
            - RESUMED
            - FAILED
            - CANCELED
            - SUPERSEDED
        # resources:
        #   - aws계정에 CodePipeline이 여러개면 resources로 명시적으로 지정할 필요가 있음
      State: ENABLED
      Targets: 
        - Arn: !GetAtt HelloWorldFunction.Arn
          Id: HelloWorldFunctionTarget

  HelloWorldFunctionPermission: 
    Type: AWS::Lambda::Permission
    Properties: 
      FunctionName: 
        Ref: HelloWorldFunction
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt HelloWorldFunctionEventRule.Arn